### ISSUE TITLE
error npm install

### ISSUE THREAD

**Issue by marz-hunter** [makuga01/dnsFookup#5]
root@instance-2:~/dnsFookup/FE# npm install
loadDep:workbox-webpack-p ▀ ╢███████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 5.4.0-1029-gcp
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/dnsFookup/FE/npm-debug.log

**Comment by marz-hunter** [comment]
root@instance-2:~/dnsFookup/FE# npm -v
3.5.2

**Comment by marz-hunter** [comment]
marz@instance-2:~/dnsFookup/FE$ npm start

> my-app@0.1.0 start /home/marz/dnsFookup/FE
> react-scripts start

sh: 1: react-scripts: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! my-app@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the my-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marz/.npm/_logs/2020-12-10T01_59_16_497Z-debug.log


I tried to install again on a different server. now when I npm start I get that error. can you provide more details about how and steps for the installation?

**Comment by marz-hunter** [comment]
server spec:
1.ubuntu server v.18 8gb RAM
2.ubuntu server v.20 16gb RAM

**Comment by balbalu** [comment]
![image](https://user-images.githubusercontent.com/38427882/112450667-9fb68e80-8d7a-11eb-9728-37300398ce3c.png)

I am having this issue

**Comment by makuga01** [comment]
@balbalu try an older python maybe and @marz-hunter sorry for the late reply bro 😅 if you are still struggling, try removing the node_modules folder in /FE and then run npm install
